# -*- coding: utf-8 -*-
"""cnn_v3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vnc0g2L3bMtdHXhcdc7UG3PiJSNVn9G

In this notebook, we will be creating a CNN (Convolutional Neural Network) based classifier for the classification of CIFAR-10 dataset.

**About the dataset**

CIFAR-10 dataset is a subset of CIFAR-100 having 80 million images of 100 different objects. CIFAR-10 takes 60,000 images for 10 classes from the original dataset in which 50,000 images are for training and 10,000 images are for testing.

The classes in the dataset are -
* airplane
* automobile
* bird
* cat
* deer
* dog
* frog
* horse
* ship
* truck
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i])
    # The CIFAR labels happen to be arrays,
    # which is why you need the extra index
    plt.xlabel(class_names[train_labels[i][0]])
plt.show()

"""**Creating a CNN model**

We are going to create a CNN based classification model using *keras* module.
"""

model = models.Sequential()

# This new Input layer fixes the red UserWarning in your screenshot!
model.add(layers.Input(shape=(32, 32, 3)))

# Layer 1
model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Layer 2
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Layer 3
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

# Layer 4 (Your new addition!)
# We increase the filters to 128 to help it learn more complex patterns
model.add(layers.Conv2D(128, (3, 3), activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

model.summary()

model.compile(optimizer='sgd',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
history = model.fit(train_images, train_labels, epochs=10,validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print(test_acc)

model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
history = model.fit(train_images, train_labels, epochs=10,validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print(test_acc)

# save model
model.save('final_model.keras') #previously saved as 'final_model.h5", a legacy

# make a prediction for new images
import tensorflow as tf
from tensorflow.keras import preprocessing
from tensorflow.keras import models
import numpy as np
import matplotlib.pyplot as plt # We added this to draw the images!

# Re-define class names just to be safe
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

def load_image(filename):
	# load the image
	img = preprocessing.image.load_img(filename, target_size=(32, 32))
	# convert to array
	img = preprocessing.image.img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

def run_example():
	# Load the model
	model = models.load_model('final_model.keras')

	# Your exact file names
	my_images = ['airplane.jpg', 'bird1.jpg', 'ship.jpg', 'deer_capture_0.png']

	print("--- Starting Predictions ---")
	for img_name in my_images:
		try:
			img = load_image(img_name)
			pred_list = model.predict(img)

			# --- NEW PERCENTAGE MATH ---
			# 1. Convert the raw output numbers into probability percentages
			probabilities = tf.nn.softmax(pred_list[0])

			# 2. Find the index of the highest percentage
			result = np.argmax(probabilities)

			# 3. Get the actual class name and the highest percentage value (multiplied by 100)
			prediction = class_names[result]
			confidence = probabilities[result] * 100
			# ---------------------------

			# Updated print statement to show the percentage rounded to 2 decimal places
			print(f"\nFile: {img_name} --> AI Prediction: {prediction} ({confidence:.2f}%)")

			# Draw the 32x32 image on the screen
			plt.figure(figsize=(2,2))
			plt.imshow(img[0])
			# Updated title to show the percentage on the graph
			plt.title(f"AI Guessed: {prediction} ({confidence:.2f}%)")
			plt.axis('off')
			plt.show()

		except FileNotFoundError:
			print(f"Error: Could not find '{img_name}'. Make sure you uploaded it to Colab!")

# run the example
run_example()